name: 'sleep-random'
description: 'Github action to sleep for random minutes or set minutes.'
author: '1itachi'
branding:
  icon: 'bell-off'  
  color: 'yellow'
inputs:
  minutes:
    required: true
    description: 'input description here'
    default: '1'
  random:
    required: false
    description: 'set the random flag to true or false'
    default: false
runs:
  using: 'node12'
  main: 'dist/index.js'
