name: 'sleep-random'
description: 'Action sleeps for set minutes or random minutes from 0 to set upper limit'
author: 'Deepak'
inputs:
  minutes: # change this
    required: true
    description: 'input description here'
    default: '1'
  random:
    required: false
    description: 'set the random flag to true or false'
    default: false
runs:
  using: 'node12'
  main: 'dist/index.js'
