name: "Release"

#Added workflow dispatch to release manually
on:
   workflow_dispatch: 
   push:
     branches: [main]

jobs:
  Release:

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: install semantic dependencies
        run: npm i -g semantic-release @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/changelog @semantic-release/npm @semantic-release/github @semantic-release/git

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}